# Generated by Django 5.2.14 on 2026-05-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('enunciado', models.TextField()),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.CharField(max_length=500)),
                ('explicacion', models.TextField(blank=True)),
                ('pagina', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
