# Generated by Django 5.2.14 on 2026-05-12 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(default='General', max_length=120),
        ),
        migrations.CreateModel(
            name='ProgresoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('veces_vista', models.IntegerField(default=0)),
                ('veces_correcta', models.IntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulador.pregunta')),
            ],
            options={
                'unique_together': {('session_key', 'pregunta')},
            },
        ),
    ]
